### ISSUE TITLE
Problem when add Where condition

### ISSUE THREAD

**Issue by halatef** [salaros/vtwsclib-php#17]
I am using the web service from a while, i moved now to a new server, but after moving all my queries which contains where conditions was stop working, only queries without condition is running 
Note: i have no errors, it just returns no results, even if all conditions are success 

i can not determine what's the exact problem which cause this

**Comment by salaros** [comment]
@halatef indeed it's strange, I've just released a new version addressing problems with where condition I personally encountered recently, please try to update to `1.0.5` and see if it works for you

This month I will add [monolog](https://packagist.org/packages/monolog/monolog) support, so that by turning verbose logging you will see all the stuff happening internally.

For now the only thing I can offer is to try to look into the problem if you create a temporary limited CRM user for me, so I can try to run some of your code snippets and debug them.

**Comment by salaros** [comment]
@halatef ?

**Comment by halatef** [comment]
@salaros it's still not working, i think it's related to server may be

**Comment by salaros** [comment]
@halatef If you create a temporary and limited CRM user for me (e.g. authorized to see just one module or even one entry of one modele) I could try to use it to investigate on the problem

**Comment by halatef** [comment]
@salaros thanks for you effort, i will check the ability of creating an account for you, since it's a shared hosting
